kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fast4-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: fast4
      labels:
        name: fast4
    spec:
      containers:
      - name: fast4
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: fast4-http
          containerPort: 8080
