kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fast4-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: fast4
      labels:
        name: fast4
    spec:
      containers:
      - name: fast4-nb
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0-nb
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: nb-http
          containerPort: 8081
      - name: fast4-pf
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0-pf
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: pf-http
          containerPort: 8080
