apiVersion: v1
kind: Service
metadata:
  name: fast4-service
  labels:
    app: fast4-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: pf-http
      targetPort: 8080
      protocol: TCP
  selector:
    app: fast4-pf
