apiVersion: v1
kind: Service
metadata:
  name: App3-service
  labels:
    app: App3-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: App3-http
      targetPort: 8080
      protocol: TCP
  selector:
    name: App3
