apiVersion: v1
kind: Service
metadata:
  name: AF40Tpl-service
  labels:
    app: AF40Tpl-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: AF40Tpl-http
      targetPort: 8080
      protocol: TCP
  selector:
    name: AF40Tpl
