kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: app3-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: app3
      labels:
        name: app3
    spec:
      containers:
      - name: app3
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: app3-http
          containerPort: 8080
